# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Classify Gaze
#'
#' Velocity based classification of raw gaze samples to discrete events such as saccades and fixations.
#'
#' @param v a vector of the instantaneous velocities for a set raw gaze samples
#' @param e a vector indicating blinks or bad data in the velocity vector
#' @param vt saccade onset velocity threshold
#' @param sigma when greater than 0, the saccade onset velocity threshold is iteratively adjusted such that
#'        the saccade onset threshold is sigma standard deviations higher than the mean of all velocity samples
#'        lower than the saccade onset threshold, when glissade detection is enabled sigma/2 is used as the
#'        saccade offset velocity threshold
#' @param minsacdur the minimum saccade duration in terms of number of samples (to obtain divide desired duration by samplerate)
#'
#'
#' @export
classify <- function(v, e, vt, sigma, minsacdur) {
    .Call('gazetools_classify', PACKAGE = 'gazetools', v, e, vt, sigma, minsacdur)
}

distance_2_point <- function(x, y, rx, ry, sw, sh, ez, ex = as.numeric( c(0.0)), ey = as.numeric( c(0.0))) {
    .Call('gazetools_distance_2_point', PACKAGE = 'gazetools', x, y, rx, ry, sw, sh, ez, ex, ey)
}

#' @export
ruidvec <- function(x) {
    .Call('gazetools_ruidvec', PACKAGE = 'gazetools', x)
}

#' @export
sigthresh <- function(x, e, threshold, sigma) {
    .Call('gazetools_sigthresh', PACKAGE = 'gazetools', x, e, threshold, sigma)
}

#' Subtended Angle
#'
#' Takes two screen coordinates and returns the angle (in degrees)
#' subtended by those two points.
#'
#' @param x1 the horizontal coordinate of the first point on a screen (pixels)
#' @param y1 the vertical coordinate of the first point on a screen (pixels)
#' @param x2 the horizontal coordinate of the second point on a screen (pixels)
#' @param y2 the vertical coordinate of the second point on a screen (pixels)
#' @param rx the horizontal resolution of the screen (pixels)
#' @param ry the vertical resolution of the screen (pixels)
#' @param sw the physical screen width (mm)
#' @param sh the physical screen height (mm)
#' @param ez the perpendicular distance from the viewer to the screen (mm)
#' @param ex the horizontal offset of the viewer from screen center (mm)
#' @param ey the vertical offset of the viewer from screen center (mm)
#'
#' @return degrees of visual angle
#'
#' @export
#'
#' @examples
#' subtended_angle(835, 525, 845, 525, 1680, 1050, 473.76, 296.1, 750)
#'
subtended_angle <- function(x1, y1, x2, y2, rx, ry, sw, sh, ez, ex = as.numeric( c(0.0)), ey = as.numeric( c(0.0))) {
    .Call('gazetools_subtended_angle', PACKAGE = 'gazetools', x1, y1, x2, y2, rx, ry, sw, sh, ez, ex, ey)
}

#' @export
uidvec <- function(x) {
    .Call('gazetools_uidvec', PACKAGE = 'gazetools', x)
}

