# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
classify <- function(x, e, vt = 100, sigma = 6) {
  .Call('gazetools_classify', PACKAGE = 'gazetools', x, e, vt, sigma)
}

#' Distance to Point
#'
#' Takes an x and y screen coordinate and returns the physical distance
#' from the observer to that point on the screen.
#'
#' @param x the horizontal coordinate of a point on a screen (pixels)
#' @param y the vertical coordinate of a point on a screen (pixels)
#' @param rx the horizontal resolution of the screen (pixels)
#' @param ry the vertical resolution of the screen (pixels)
#' @param sw the physical screen width (mm)
#' @param sh the physical screen height (mm)
#' @param ez the perpendicular distance from the viewer to the screen (mm)
#' @param ex the horizontal offset of the viewer from screen center (mm)
#' @param ey the vertical offset of the viewer from screen center (mm)
#'
#' @export
#'
#' @examples
#' distance_2_point(840, 525, 1680, 1050, 473.76, 296.1, 750)
#'
distance_2_point <- function(x, y, rx, ry, sw, sh, ez, ex=0.0, ey=0.0) {
  N <-length(x)
  if (length(ez)==1) ez <- rep(ez,N)
  if (length(ex)==1) ex <- rep(ex,N)
  if (length(ey)==1) ey <- rep(ey,N)
  .Call('gazetools_distance_2_point', PACKAGE = 'gazetools', x, y, rx, ry, sw, sh, ez, ex, ey)
}

#' @export
ruidvec <- function(x) {
  .Call('gazetools_ruidvec', PACKAGE = 'gazetools', x)
}

#' @export
sigthresh <- function(x, e, threshold, sigma) {
  .Call('gazetools_sigthresh', PACKAGE = 'gazetools', x, e, threshold, sigma)
}

#' Subtended Angle
#'
#' Takes two screen coordinates and returns the angle (in degrees)
#' subtended by those two points.
#'
#' @param x1 the horizontal coordinate of the first point on a screen (pixels)
#' @param y1 the vertical coordinate of the first point on a screen (pixels)
#' @param x2 the horizontal coordinate of the second point on a screen (pixels)
#' @param y2 the vertical coordinate of the second point on a screen (pixels)
#' @param rx the horizontal resolution of the screen (pixels)
#' @param ry the vertical resolution of the screen (pixels)
#' @param sw the physical screen width (mm)
#' @param sh the physical screen height (mm)
#' @param ez the perpendicular distance from the viewer to the screen (mm)
#' @param ex the horizontal offset of the viewer from screen center (mm)
#' @param ey the vertical offset of the viewer from screen center (mm)
#'
#' @return degrees of visual angle
#'
#' @export
#'
#' @examples
#' subtended_angle(835, 525, 845, 525, 1680, 1050, 473.76, 296.1, 750)
#'
subtended_angle <- function(x1, y1, x2, y2, rx, ry, sw, sh, ez, ex=0.0, ey=0.0) {
  N <-length(x1)
  if (length(ez)==1) ez <- rep(ez,N)
  if (length(ex)==1) ex <- rep(ex,N)
  if (length(ey)==1) ey <- rep(ey,N)
  .Call('gazetools_subtended_angle', PACKAGE = 'gazetools', x1, y1, x2, y2, rx, ry, sw, sh, ez, ex, ey)
}

#' @export
uidvec <- function(x) {
  .Call('gazetools_uidvec', PACKAGE = 'gazetools', x)
}
